services:
  identidock: 
    build: .
    expose: 
      - "9090"
    environment: 
      - ENV=PROD
    volumes: 
      - ./app:/app
    links:
      - dnmonster
      - redis

  dnmonster:
    image: amouat/dnmonster:latest

  redis:
    image: redis:latest
